# Generated by Django 4.2.5 on 2023-09-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
    ]
